package constants

object EnvVariables
{
  val SMS_SENDER_ID = "SMS_SENDER_ID"

  val SMS_TYPE = "SMS_TYPE"

  val SMS_MAX_PRICE = "SMS_MAX_PRICE"

  val AIRTABLE_SERVICE_URL = "AIRTABLE_SERVICE_URL"

  val PASSCODE_LENGTH = "PASSCODE_LENGTH"
}